name: Deploy Discord Bot

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Configure AWS Credentials (OIDC Role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ap-northeast-1

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Package with CloudFormation
        run: |
          aws cloudformation package \
            --template-file infrastructure/cloudformation.yml \
            --s3-bucket ${{ secrets.S3_ARTIFACT_BUCKET_NAME }}
            --output-template-file packaged.yml

      - name: Deploy with CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file packaged.yml \
            --stack-name discord-bot-stack \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              DiscordPublicKey=${{ secrets.DISCORD_PUBLIC_KEY }}
