name: Deploy Discord Bot

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    branches:
      - feature/setup-commands

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Configure AWS Credentials (OIDC Role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ap-northeast-1

      - name: Store Discord Bot Token in SSM Parameter Store
        run: |
          aws ssm put-parameter \
            --name "/discord-event-bot/DISCORD_BOT_TOKEN" \
            --value "${{ secrets.DISCORD_BOT_TOKEN }}" \
            --type "SecureString" \
            --overwrite \
            --description "Discord Bot Token for Event Bot"

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Install production dependencies in dist
        run: |
          cp package.json package-lock.json dist/
          cd dist
          npm ci --production
          cd ..

      - name: Package with CloudFormation
        run: |
          aws cloudformation package \
            --template-file infrastructure/template.yml \
            --s3-bucket ${{ secrets.S3_ARTIFACT_BUCKET_NAME }} \
            --output-template-file packaged.yml

      - name: Deploy with CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file packaged.yml \
            --stack-name discord-bot-stack \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              DiscordPublicKey=${{ secrets.DISCORD_PUBLIC_KEY }} \
              DiscordApplicationId=${{ secrets.DISCORD_APPLICATION_ID }}
